---
title: "nMDS with smaller data set"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Classification Procedure (Sal's Code)
```{r}
library(tidyverse, quietly = TRUE)
library(vegclust, quietly = TRUE)
library(rpart, quietly = TRUE)
library(infotheo, quietly = TRUE)
library(cluster, quietly = TRUE)

#Load in the data that will be used for clustering
load_data <- function(dom_species){

  df <- read_csv("clean_data/UMRS_FPF_clean.csv")
  labels <- read_csv("clean_data/plot_classification.csv")

  df_cols <- left_join(df, labels, by = "PID") %>% select(PID, TR_SP, TR_DIA, BasalArea, TreesPerAcre, Type, Label) %>% filter(Type == dom_species)
  return(df_cols)
}

#Produce the dissimilarity matrix for the given dominant species type
dissimilarity_matrix <- function(df, meth = "manhattan"){
  #106 is the max... for some reason only works if 106 is hardcoded
  TPA_bins = 1 / (pi * (seq(1:106)*2.75)^2) / 43560
  BA_bins = 0.25*pi*(seq(1:106)^2)
  
  cap <- stratifyvegdata(df, sizes1 = BA_bins, plotColumn = "PID", speciesColumn = "TR_SP", abundanceColumn = "TreesPerAcre", size1Column = "BasalArea", cumulative = TRUE )
  d <- vegdiststruct(cap, method = meth)
  return(d)
}

#Classification output for a single dominant species type
#This needs to be tested, and introspection must be able to be performed
best_clustering <- function(df, dissim, max_clusters, meth = "ward.D2"){
  
  cluster_h <- hclust(as.dist(dissim), method = meth)
  
  plot_abundance <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(TPA = sum(TreesPerAcre)) %>%
    replace(is.na(.), 0) 
  
  plot_size <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(BA = sum(BasalArea)) %>%
    replace(is.na(.), 0)
  
  plots <- inner_join(plot_abundance, plot_size, by = c("PID", "TR_SP")) %>% 
    pivot_wider(names_from = TR_SP, values_from = c(TPA, BA)) %>% 
    replace(is.na(.), 0)
  
  plots <- left_join(plots, read_csv("clean_data/plot_classification.csv"))
  #form <- paste( "cluster ~", paste0(colnames(plots)[2:(ncol(plots)-2)], collapse = " + "))
  
  num <- min(max_clusters, nrow(plots))
  
  sil <- vector("list", length = num-1)
  for(n in 2:num){
    plots$cluster <- cutree(cluster_h, k = n)
    sil[[n-1]] <- mean(silhouette(x = plots$cluster, dmatrix = as.matrix(dissim))[,"sil_width"])
  }
  plots$cluster <- cutree(cluster_h, k = (which.max(sil)+1))
  return(plots)
}

classify <- function(max_clusters_num){
  df <- read_csv("clean_data/UMRS_FPF_clean.csv")
  labels <- read_csv("clean_data/plot_classification.csv")
  df <- left_join(df, labels, by = "PID")
  df_cols_total <- df %>% filter(Label != "Mixed") %>% filter(Type %in% (df %>% group_by(Type) %>% summarize(Count = n_distinct(PID)) %>% filter(Count > 10))$Type)
  
  df <- load_data("ACNE2")
  dissim <- dissimilarity_matrix(df)
  result <- best_clustering(df, dissim, 10)

  for(dom_species in unique(df_cols_total$Type)[unique(df_cols_total$Type) != "ACNE2"]){
    print(dom_species)
    df <- load_data(dom_species)
    dissim <- dissimilarity_matrix(df)
    best <- best_clustering(df, dissim, 10)
    result <- rbind(result, best)

  }
  
  return(result)
}

final <- classify(10)
new_final <- final %>% select(PID, Type, Label, cluster)
write_csv(final, "classified_plots_full.csv")
write_csv(new_final, "classified_plots_labels.csv")

results <- final %>% group_by(Type) %>% summarize(clusters = max(cluster), plots = n_distinct(PID))
ggplot(results, aes(x = clusters, y = plots)) + geom_col()
ggplot(results, aes(x = clusters)) + geom_histogram(binwidth=1)      

```
Sal's code 
```{r}
library(ggsci)
library(rpart.plot)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

#source("classification_procedure.R")
###########################################################
library(tidyverse)
library(vegclust)
library(rpart)
library(infotheo)

#Load in the data that will be used for clustering
load_data <- function(dom_species){
  path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
  setwd(path_of_code)

  df <- read_csv("clean_data/UMRS_FPF_clean.csv")
  labels <- read_csv("clean_data/plot_classification.csv")

  df_cols <- left_join(df, labels, by = "PID") %>% select(PID, TR_SP, TR_DIA, BasalArea, TreesPerAcre, Type, Label) %>% filter(Type == dom_species)
  return(df_cols)
}

#Produce the dissimilarity matrix for the given dominant species type
dissim <- function(df, meth = "manhattan"){
  
  TPA_bins = 1 / (pi * (seq(1:max(df$TR_DIA))*2.75)^2) / 43560
  BA_bins = 0.25*pi*(seq(1:max(df$TR_DIA))^2)
  
  cap <- stratifyvegdata(df, sizes1 = BA_bins, plotColumn = "PID", speciesColumn = "TR_SP", abundanceColumn = "TreesPerAcre", size1Column = "BasalArea", cumulative = TRUE )
  d <- vegdiststruct(cap, method = meth)
  return(d)
}

#Classification output for a single dominant species type
#This needs to be tested, and introspection must be able to be performed
best_clustering <- function(df, dissim, dom_species, max_clusters, meth = "ward.D2"){
  cluster_h <- hclust(as.dist(dissim), method = meth)
  
  plot_abundance <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(TPA = sum(TreesPerAcre)) %>%
    replace(is.na(.), 0) 
  
  plot_size <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(BA = sum(BasalArea)) %>%
    replace(is.na(.), 0)
  
  plots <- inner_join(plot_abundance, plot_size, by = c("PID", "TR_SP")) %>% 
    pivot_wider(names_from = TR_SP, values_from = c(TPA, BA)) %>% 
    replace(is.na(.), 0)
  
  plots <- left_join(plots, read_csv("clean_data/plot_classification.csv"))
  
  form <- paste( "cluster ~", paste0(colnames(plots)[2:(ncol(plots)-2)], collapse = " + "))
  
  vmeasures <- vector(length = max_clusters - 1)
  trees <- vector("list",length = max_clusters - 1)
  for(n in 2:max_clusters){
    cut <- cutree(cluster_h, k = n)
    plots$cluster <- cut
    
    trees[[n-1]] <- rpart(data = plots, formula = form, method = "class", control = rpart.control(maxdepth = ceiling(log(2*n,2)), cp = 0, minbucket = 1))
    sel_tree <- trees[[n-1]]
    plots$tree <- predict(sel_tree, plots, type = "vector")
    
    h <- 1 - condentropy(plots$cluster, plots$tree) / entropy(plots$cluster)
    c <- 1 - condentropy(plots$tree, plots$cluster) / entropy(plots$tree)
    
    vmeasures[n-1] <- 2 * ((h*c) / (h + c))
  }
  
  best_k <- which.max(vmeasures)
  
  plots$cluster <- predict(trees[[best_k]], plots, type = "vector")
  plots <- select(plots, -tree)
  return(list(plots, trees[[best_k]]))
}
###########################################################
#Willow 
SALIX <- load_data("SALIX")
d <- dissim(SALIX)
process <- best_clustering(SALIX, d, "SALIX", 20)
test <- process[[1]]
test_tree <- process[[2]]
rpart.plot(test_tree)
ggplot(test) + geom_point(aes(x = log(TPA_SALIX), y = log(BA_SALIX), color = as.factor(cluster))) + scale_color_jco() + theme_light()

#there is clearly an issue - sometimes, a cluster will be too insignificant to be picked out by the decision tree. In this case, what should we do? (-Sal)

```
##Willow nMDS 
```{r}
library(vegan)
ptm <- proc.time()
SALIX.mds2<-metaMDS(d,distance="manhattan",k=2, trymax=1000,maxit=1000) 
proc.time() - ptm
```

```{r}
plot(SALIX.mds2)
```
##scree plot
```{r}
#didn't do scree plot because the NMDS wouldn't converge with other dimensions 
#library(vegan)
#library(goeveg)
#dimcheckMDS(as.matrix(d), distance = "manhattan", k = 4, trymax = 1000, maxit=1000, autotransform = TRUE)
```
## exploration 
```{r}
names(SALIX.mds2)
SALIX.mds2
#species names are missing 
SALIX.mds2$species #(NA)
```
"Add or Replace Spec/s Scores in Distance-Based Ordination" for Willow, k=2
```{r}
library(readr)
sppscores(SALIX.mds2) <- d
SALIX.mds2$species
plot(SALIX.mds2)
SALIX.mds2.df<-data.frame(SALIX.mds2$species)
SALIX.mds2.df
write_csv(SALIX.mds2.df, "SALIX.mds2.df.csv")
nmds.df<-read_csv("SALIX.mds2.df.csv")
``` 

```{r}
library(readr)
library(dplyr)
plot_classification <- read_csv("~/Desktop/REU /git/UWL-REU-FPF/clean_data/plot_classification.csv")
plot_classificationSALIX <-plot_classification %>% 
  filter(Type == "SALIX")
plot_classificationSALIX<-subset(plot_classificationSALIX,select=-c(Type,Label))
SALIX.full.df<-cbind(plot_classificationSALIX,nmds.df)
SALIX.full.df
write_csv(SALIX.full.df, "SALIX.full.df.csv")
```
nmds plot, Willow 
```{r}
library(tidyverse)
library(ggsci)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

labels <- read_csv("classified_plots_labels.csv")
coords <- read_csv("SALIX.full.df.csv")
nmds <- left_join(coords, labels, by = "PID")

nmds

#ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + labs(title= "nMDS Willow") + scale_color_jco() + theme_light() 

ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + labs(title= "nMDS Willow") + scale_color_jco() + theme(title=element_text(size=18), axis.text=element_text(size=15),legend.text=element_text(size=15))+labs(color="Cluster")

```
Same process for Silver Maple 
```{r}
library(ggsci)
library(rpart.plot)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

#source("classification_procedure.R")
###########################################################
library(tidyverse)
library(vegclust)
library(rpart)
library(infotheo)

#Load in the data that will be used for clustering
load_data <- function(dom_species){
  path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
  setwd(path_of_code)

  df <- read_csv("clean_data/UMRS_FPF_clean.csv")
  labels <- read_csv("clean_data/plot_classification.csv")

  df_cols <- left_join(df, labels, by = "PID") %>% select(PID, TR_SP, TR_DIA, BasalArea, TreesPerAcre, Type, Label) %>% filter(Type == dom_species)
  return(df_cols)
}

#Produce the dissimilarity matrix for the given dominant species type
dissim <- function(df, meth = "manhattan"){
  
  TPA_bins = 1 / (pi * (seq(1:max(df$TR_DIA))*2.75)^2) / 43560
  BA_bins = 0.25*pi*(seq(1:max(df$TR_DIA))^2)
  
  cap <- stratifyvegdata(df, sizes1 = BA_bins, plotColumn = "PID", speciesColumn = "TR_SP", abundanceColumn = "TreesPerAcre", size1Column = "BasalArea", cumulative = TRUE )
  d <- vegdiststruct(cap, method = meth)
  return(d)
}

#Classification output for a single dominant species type
#This needs to be tested, and introspection must be able to be performed
best_clustering <- function(df, dissim, dom_species, max_clusters, meth = "ward.D2"){
  cluster_h <- hclust(as.dist(dissim), method = meth)
  
  plot_abundance <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(TPA = sum(TreesPerAcre)) %>%
    replace(is.na(.), 0) 
  
  plot_size <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(BA = sum(BasalArea)) %>%
    replace(is.na(.), 0)
  
  plots <- inner_join(plot_abundance, plot_size, by = c("PID", "TR_SP")) %>% 
    pivot_wider(names_from = TR_SP, values_from = c(TPA, BA)) %>% 
    replace(is.na(.), 0)
  
  plots <- left_join(plots, read_csv("clean_data/plot_classification.csv"))
  
  form <- paste( "cluster ~", paste0(colnames(plots)[2:(ncol(plots)-2)], collapse = " + "))
  
  vmeasures <- vector(length = max_clusters - 1)
  trees <- vector("list",length = max_clusters - 1)
  for(n in 2:max_clusters){
    cut <- cutree(cluster_h, k = n)
    plots$cluster <- cut
    
    trees[[n-1]] <- rpart(data = plots, formula = form, method = "class", control = rpart.control(maxdepth = ceiling(log(2*n,2)), cp = 0, minbucket = 1))
    sel_tree <- trees[[n-1]]
    plots$tree <- predict(sel_tree, plots, type = "vector")
    
    h <- 1 - condentropy(plots$cluster, plots$tree) / entropy(plots$cluster)
    c <- 1 - condentropy(plots$tree, plots$cluster) / entropy(plots$tree)
    
    vmeasures[n-1] <- 2 * ((h*c) / (h + c))
  }
  
  best_k <- which.max(vmeasures)
  
  plots$cluster <- predict(trees[[best_k]], plots, type = "vector")
  plots <- select(plots, -tree)
  return(list(plots, trees[[best_k]]))
}

ACSA2 <- load_data("ACSA2")
d <- dissim(ACSA2)
process <- best_clustering(ACSA2, d, "ACSA2", 20)
test <- process[[1]]
test_tree <- process[[2]]
rpart.plot(test_tree)
ggplot(test) + geom_point(aes(x = log(TPA_ACSA2), y = log(BA_ACSA2), color = as.factor(cluster))) + scale_color_jco() + theme_light()

library(vegan)
ptm <- proc.time()
ACSA2.mds2<-metaMDS(d,distance="manhattan",k=2, trymax=1000,maxit=1000) 
proc.time() - ptm
plot(ACSA2.mds2)

library(readr)
sppscores(ACSA2.mds2) <- d
ACSA2.mds2$species
plot(ACSA2.mds2)
ACSA2.mds2.df<-data.frame(ACSA2.mds2$species)
ACSA2.mds2.df
write_csv(ACSA2.mds2.df, "ACSA2.mds2.df.csv")
nmds.df<-read_csv("ACSA2.mds2.df.csv")

library(readr)
library(dplyr)
plot_classification <- read_csv("~/Desktop/REU /git/UWL-REU-FPF/clean_data/plot_classification.csv")
plot_classificationACSA2 <-plot_classification %>% 
  filter(Type == "ACSA2")
plot_classificationACSA2<-subset(plot_classificationACSA2,select=-c(Type,Label))
ACSA2.full.df<-cbind(plot_classificationACSA2,nmds.df)
ACSA2.full.df
write_csv(ACSA2.full.df, "ACSA2.full.df.csv")
```
nmds plot, silver maple 
```{r}
library(tidyverse)
library(ggsci)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

labels <- read_csv("classified_plots_labels.csv")
coords <- read_csv("ACSA2.full.df.csv")
nmds <- left_join(coords, labels, by = "PID")

nmds

ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + scale_color_jco() + theme_light()

ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + labs(title= "nMDS Silver Maple") + scale_color_jco() + theme(title=element_text(size=18), axis.text=element_text(size=15),legend.text=element_text(size=15))+labs(color="Cluster")
```
Cottonwood: PODE3
```{r}
library(ggsci)
library(rpart.plot)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

#source("classification_procedure.R")
###########################################################
library(tidyverse)
library(vegclust)
library(rpart)
library(infotheo)

#Load in the data that will be used for clustering
load_data <- function(dom_species){
  path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
  setwd(path_of_code)

  df <- read_csv("clean_data/UMRS_FPF_clean.csv")
  labels <- read_csv("clean_data/plot_classification.csv")

  df_cols <- left_join(df, labels, by = "PID") %>% select(PID, TR_SP, TR_DIA, BasalArea, TreesPerAcre, Type, Label) %>% filter(Type == dom_species)
  return(df_cols)
}

#Produce the dissimilarity matrix for the given dominant species type
dissim <- function(df, meth = "manhattan"){
  
  TPA_bins = 1 / (pi * (seq(1:max(df$TR_DIA))*2.75)^2) / 43560
  BA_bins = 0.25*pi*(seq(1:max(df$TR_DIA))^2)
  
  cap <- stratifyvegdata(df, sizes1 = BA_bins, plotColumn = "PID", speciesColumn = "TR_SP", abundanceColumn = "TreesPerAcre", size1Column = "BasalArea", cumulative = TRUE )
  d <- vegdiststruct(cap, method = meth)
  return(d)
}

#Classification output for a single dominant species type
#This needs to be tested, and introspection must be able to be performed
best_clustering <- function(df, dissim, dom_species, max_clusters, meth = "ward.D2"){
  cluster_h <- hclust(as.dist(dissim), method = meth)
  
  plot_abundance <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(TPA = sum(TreesPerAcre)) %>%
    replace(is.na(.), 0) 
  
  plot_size <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(BA = sum(BasalArea)) %>%
    replace(is.na(.), 0)
  
  plots <- inner_join(plot_abundance, plot_size, by = c("PID", "TR_SP")) %>% 
    pivot_wider(names_from = TR_SP, values_from = c(TPA, BA)) %>% 
    replace(is.na(.), 0)
  
  plots <- left_join(plots, read_csv("clean_data/plot_classification.csv"))
  
  form <- paste( "cluster ~", paste0(colnames(plots)[2:(ncol(plots)-2)], collapse = " + "))
  
  vmeasures <- vector(length = max_clusters - 1)
  trees <- vector("list",length = max_clusters - 1)
  for(n in 2:max_clusters){
    cut <- cutree(cluster_h, k = n)
    plots$cluster <- cut
    
    trees[[n-1]] <- rpart(data = plots, formula = form, method = "class", control = rpart.control(maxdepth = ceiling(log(2*n,2)), cp = 0, minbucket = 1))
    sel_tree <- trees[[n-1]]
    plots$tree <- predict(sel_tree, plots, type = "vector")
    
    h <- 1 - condentropy(plots$cluster, plots$tree) / entropy(plots$cluster)
    c <- 1 - condentropy(plots$tree, plots$cluster) / entropy(plots$tree)
    
    vmeasures[n-1] <- 2 * ((h*c) / (h + c))
  }
  
  best_k <- which.max(vmeasures)
  
  plots$cluster <- predict(trees[[best_k]], plots, type = "vector")
  plots <- select(plots, -tree)
  return(list(plots, trees[[best_k]]))
}

PODE3 <- load_data("PODE3")
d <- dissim(PODE3)
process <- best_clustering(PODE3, d, "PODE3", 20)
test <- process[[1]]
test_tree <- process[[2]]
rpart.plot(test_tree)
ggplot(test) + geom_point(aes(x = log(TPA_PODE3), y = log(BA_PODE3), color = as.factor(cluster))) + scale_color_jco() + theme_light()

library(vegan)
ptm <- proc.time()
PODE3.mds2<-metaMDS(d,distance="manhattan",k=2, trymax=500,maxit=500) 
proc.time() - ptm
plot(PODE3.mds2)

library(readr)
sppscores(PODE3.mds2) <- d
PODE3.mds2$species
plot(PODE3.mds2)
PODE3.mds2.df<-data.frame(PODE3.mds2$species)
PODE3.mds2.df
write_csv(PODE3.mds2.df, "PODE3.mds2.df.csv")
nmds.df<-read_csv("PODE3.mds2.df.csv")

library(readr)
library(dplyr)
plot_classification <- read_csv("~/Desktop/REU /git/UWL-REU-FPF/clean_data/plot_classification.csv")
plot_classificationPODE3 <-plot_classification %>% 
  filter(Type == "PODE3")
plot_classificationPODE3<-subset(plot_classificationPODE3,select=-c(Type,Label))
PODE3.full.df<-cbind(plot_classificationPODE3,nmds.df)
PODE3.full.df
write_csv(PODE3.full.df, "PODE3.full.df.csv")
```
nmds plot, cottonwood 
```{r}
library(tidyverse)
library(ggsci)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

labels <- read_csv("classified_plots_labels.csv")
coords <- read_csv("PODE3.full.df.csv")
nmds <- left_join(coords, labels, by = "PID")

nmds

ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + scale_color_jco() + theme_light()

ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + labs(title= "nMDS Cottonwood") + scale_color_jco() + theme(title=element_text(size=18), axis.text=element_text(size=15),legend.text=element_text(size=15))+labs(color="Cluster")
```
Green Ash 
```{r}
library(ggsci)
library(rpart.plot)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

#source("classification_procedure.R")
###########################################################
library(tidyverse)
library(vegclust)
library(rpart)
library(infotheo)

#Load in the data that will be used for clustering
load_data <- function(dom_species){
  path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
  setwd(path_of_code)

  df <- read_csv("clean_data/UMRS_FPF_clean.csv")
  labels <- read_csv("clean_data/plot_classification.csv")

  df_cols <- left_join(df, labels, by = "PID") %>% select(PID, TR_SP, TR_DIA, BasalArea, TreesPerAcre, Type, Label) %>% filter(Type == dom_species)
  return(df_cols)
}

#Produce the dissimilarity matrix for the given dominant species type
dissim <- function(df, meth = "manhattan"){
  
  TPA_bins = 1 / (pi * (seq(1:max(df$TR_DIA))*2.75)^2) / 43560
  BA_bins = 0.25*pi*(seq(1:max(df$TR_DIA))^2)
  
  cap <- stratifyvegdata(df, sizes1 = BA_bins, plotColumn = "PID", speciesColumn = "TR_SP", abundanceColumn = "TreesPerAcre", size1Column = "BasalArea", cumulative = TRUE )
  d <- vegdiststruct(cap, method = meth)
  return(d)
}

#Classification output for a single dominant species type
#This needs to be tested, and introspection must be able to be performed
best_clustering <- function(df, dissim, dom_species, max_clusters, meth = "ward.D2"){
  cluster_h <- hclust(as.dist(dissim), method = meth)
  
  plot_abundance <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(TPA = sum(TreesPerAcre)) %>%
    replace(is.na(.), 0) 
  
  plot_size <- df %>%
    group_by(PID, TR_SP) %>%
    summarize(BA = sum(BasalArea)) %>%
    replace(is.na(.), 0)
  
  plots <- inner_join(plot_abundance, plot_size, by = c("PID", "TR_SP")) %>% 
    pivot_wider(names_from = TR_SP, values_from = c(TPA, BA)) %>% 
    replace(is.na(.), 0)
  
  plots <- left_join(plots, read_csv("clean_data/plot_classification.csv"))
  
  form <- paste( "cluster ~", paste0(colnames(plots)[2:(ncol(plots)-2)], collapse = " + "))
  
  vmeasures <- vector(length = max_clusters - 1)
  trees <- vector("list",length = max_clusters - 1)
  for(n in 2:max_clusters){
    cut <- cutree(cluster_h, k = n)
    plots$cluster <- cut
    
    trees[[n-1]] <- rpart(data = plots, formula = form, method = "class", control = rpart.control(maxdepth = ceiling(log(2*n,2)), cp = 0, minbucket = 1))
    sel_tree <- trees[[n-1]]
    plots$tree <- predict(sel_tree, plots, type = "vector")
    
    h <- 1 - condentropy(plots$cluster, plots$tree) / entropy(plots$cluster)
    c <- 1 - condentropy(plots$tree, plots$cluster) / entropy(plots$tree)
    
    vmeasures[n-1] <- 2 * ((h*c) / (h + c))
  }
  
  best_k <- which.max(vmeasures)
  
  plots$cluster <- predict(trees[[best_k]], plots, type = "vector")
  plots <- select(plots, -tree)
  return(list(plots, trees[[best_k]]))
}
FRPE <- load_data("FRPE")
d <- dissim(FRPE)
process <- best_clustering(FRPE, d, "FRPE", 20)
test <- process[[1]]
test_tree <- process[[2]]
rpart.plot(test_tree)
ggplot(test) + geom_point(aes(x = log(TPA_FRPE), y = log(BA_FRPE), color = as.factor(cluster))) + scale_color_jco() + theme_light()

library(vegan)
ptm <- proc.time()
FRPE.mds2<-metaMDS(d,distance="manhattan",k=2, trymax=1000,maxit=1000) 
proc.time() - ptm
plot(FRPE.mds2)

library(readr)
sppscores(FRPE.mds2) <- d
FRPE.mds2$species
plot(FRPE.mds2)
FRPE.mds2.df<-data.frame(FRPE.mds2$species)
FRPE.mds2.df
write_csv(FRPE.mds2.df, "FRPE.mds2.df.csv")
nmds.df<-read_csv("FRPE.mds2.df.csv")

library(readr)
library(dplyr)
plot_classification <- read_csv("~/Desktop/REU /git/UWL-REU-FPF/clean_data/plot_classification.csv")
plot_classificationFRPE <-plot_classification %>% 
  filter(Type == "FRPE")
plot_classificationFRPE<-subset(plot_classificationFRPE,select=-c(Type,Label))
FRPE.full.df<-cbind(plot_classificationFRPE,nmds.df)
FRPE.full.df
write_csv(FRPE.full.df, "FRPE.full.df.csv")
```
nmds plot, green ash 
```{r}
library(tidyverse)
library(ggsci)

path_of_code <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(path_of_code)

labels <- read_csv("classified_plots_labels.csv")
coords <- read_csv("FRPE.full.df.csv")
nmds <- left_join(coords, labels, by = "PID")

nmds

ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + scale_color_jco() + theme_light()

ggplot(nmds) + geom_point(aes(x = MDS1, y = MDS2, color = as.factor(cluster))) + labs(title= "nMDS Green Ash") + scale_color_jco() + theme(title=element_text(size=18), axis.text=element_text(size=15),legend.text=element_text(size=15))+labs(color="Cluster")
```

